version: '3.2'

services:
  nginx:
      image: rezamda/com.reza.sample.docker-nginx:latest
      container_name: nginx
      environment:
        CONFD_BACKEND: 'http://vault-server:8200'
        CONFD_BACKEND_TYPE: 'vault'
        CONFD_APPROLE: 'read-config-approle'
      volumes:
          - ./share/secret/.read-config-approle_role_id:/vault/secret/.read-config-approle_role_id:ro
          - ./share/secret/.read-config-approle_secret_id:/vault/secret/.read-config-approle_secret_id:ro
      networks:
        - http-default
  tomcat:
      image: rezamda/com.reza.sample.docker-tomcat:latest
      container_name: tomcat
      environment:
        CONFD_BACKEND: 'http://vault-server:8200'
        CONFD_BACKEND_TYPE: 'vault'
        CONFD_APPROLE: 'read-config-approle'
      volumes:
          - ./share/secret/.read-config-approle_role_id:/vault/secret/.read-config-approle_role_id:ro
          - ./share/secret/.read-config-approle_secret_id:/vault/secret/.read-config-approle_secret_id:ro
      ports:
        - "8080:8080"
      networks:
        - http-default
networks:
  http-default: