version: '3.2'

services:
  vault-server:
      image: rezamda/com.reza.sample.docker-vault-server:latest
      container_name: vault-server
      networks:
         - http-default
      volumes:
          - ./share/file:/vault/file:rw
      ports:
         - "8200:8200"
  vault-client:
      image: rezamda/com.reza.sample.docker-vault-client:latest
      container_name: vault-client
      networks:
         - http-default
      volumes:
          - ./share/secret:/vault/client/secret:rw
      depends_on:
        - vault-server
networks:
  http-default: