version: '3.2'

services:
  nginx:
      image: rezamda/com.reza.sample.docker-nginx:latest
      container_name: nginx
      environment:
        CONFD_BACKEND: 'http://vault-server:8200'
        CONFD_BACKEND_TYPE: 'vault'
        CONFD_ROLE_ID: '107335e8-ab65-2d90-0d75-593f3db67558'
        CONFD_SECRET_ID: 'faf06d1a-feba-0b37-efda-3a6e13b5dbe5'
      networks:
        - http-default
  tomcat:
      image: rezamda/com.reza.sample.docker-tomcat:latest
      container_name: tomcat
      environment:
        CONFD_BACKEND: 'http://vault-server:8200'
        CONFD_BACKEND_TYPE: 'vault'
        CONFD_ROLE_ID: '107335e8-ab65-2d90-0d75-593f3db67558'
        CONFD_SECRET_ID: 'faf06d1a-feba-0b37-efda-3a6e13b5dbe5'
      ports:
        - "8080:8080"
      networks:
        - http-default
networks:
  http-default: